# Generated by Django 4.0.3 on 2022-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tagline_one', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_two', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_three', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_four', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_five', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Impression',
                'verbose_name_plural': 'Impressions',
            },
        ),
        migrations.CreateModel(
            name='Mid_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Mid Page Image',
                'verbose_name_plural': 'Mid Page Image',
            },
        ),
        migrations.CreateModel(
            name='Our_Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tagline_one', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_two', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_three', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_four', models.TextField(blank=True, max_length=500, null=True)),
                ('tagline_five', models.TextField(blank=True, max_length=500, null=True)),
                ('pass_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('achievements', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Our Mission',
                'verbose_name_plural': 'Our Mission',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tagline_one', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline_two', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Sliders',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('testimony', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tagline_one', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('application_form', models.FileField(blank=True, null=True, upload_to='applications')),
            ],
            options={
                'verbose_name': 'Welcome',
                'verbose_name_plural': 'Welcome',
            },
        ),
    ]
