# Generated by Django 4.0.3 on 2022-04-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrassa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcome',
            name='image',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='tagline_one',
        ),
    ]
