# Generated by Django 4.0.3 on 2022-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrassa', '0002_remove_welcome_image_remove_welcome_tagline_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='image',
            new_name='image_one',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='impression',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='tagline_five',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='tagline_four',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='tagline_three',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='tagline_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
