# Generated by Django 4.0.3 on 2022-04-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrassa', '0003_rename_image_impression_image_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_mission',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='our_mission',
            name='pass_rate',
        ),
        migrations.RemoveField(
            model_name='our_mission',
            name='tagline_five',
        ),
        migrations.RemoveField(
            model_name='our_mission',
            name='tagline_four',
        ),
        migrations.RemoveField(
            model_name='our_mission',
            name='tagline_three',
        ),
        migrations.RemoveField(
            model_name='our_mission',
            name='tagline_two',
        ),
    ]
