# Generated by Django 4.0.3 on 2022-04-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrassa', '0004_remove_our_mission_achievements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mid_Page',
        ),
    ]
