# Generated by Django 4.1.1 on 2022-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrassa', '0005_delete_mid_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='image_one',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_five',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_six',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_three',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_one',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
