# Generated by Django 4.1.1 on 2022-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrassa', '0006_rename_image_slider_image_one_slider_image_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome',
            old_name='content',
            new_name='content_one',
        ),
        migrations.RenameField(
            model_name='welcome',
            old_name='title',
            new_name='title_one',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='application_form',
        ),
        migrations.AddField(
            model_name='welcome',
            name='content_two',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='welcome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='welcome',
            name='title_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
