# Generated by Django 4.1.1 on 2022-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_next_project_project_previous_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
