# Generated by Django 4.0.3 on 2022-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenClubGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/club')),
            ],
            options={
                'verbose_name': 'Green Club Gallery',
                'verbose_name_plural': 'Green Club Gallery',
            },
        ),
    ]
