# Generated by Django 4.0.3 on 2022-04-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_greenclubgallery_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreenClubGallery',
            new_name='Green_Club',
        ),
    ]
