# Generated by Django 4.0.3 on 2022-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='upload_letter',
            field=models.FileField(blank=True, upload_to='letters/'),
        ),
    ]
