# Generated by Django 4.0.3 on 2022-04-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('father', models.CharField(default='', max_length=122)),
                ('mother', models.CharField(default='', max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('phone', models.CharField(default='', max_length=12)),
                ('phone1', models.CharField(default='', max_length=12)),
                ('MhtcetAppNo', models.CharField(default='', max_length=12)),
                ('MhtcetPercentile', models.CharField(default='', max_length=12)),
                ('MhtcetRank', models.CharField(default='', max_length=12)),
                ('JeeAppNo', models.CharField(default='', max_length=12)),
                ('JeePercentile', models.CharField(default='', max_length=12)),
                ('JeeRank', models.CharField(default='', max_length=12)),
                ('Address1', models.TextField(default='')),
                ('Address2', models.TextField(default='')),
                ('CollegeName', models.CharField(default='', max_length=122)),
                ('Percentage', models.CharField(default='', max_length=12)),
                ('file', models.FileField(default='', upload_to='')),
                ('file1', models.FileField(default='', upload_to='')),
                ('Aadhar', models.CharField(default='', max_length=12)),
                ('desc', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Form',
            },
        ),
    ]
