# Generated by Django 4.0.3 on 2022-04-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_form',
            name='Aadhar',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='Address1',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='CollegeName',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='JeeAppNo',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='JeePercentile',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='JeeRank',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='MhtcetAppNo',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='MhtcetPercentile',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='MhtcetRank',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='file',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='file1',
        ),
    ]
