# Generated by Django 4.0.3 on 2022-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_form_aadhar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_form',
            name='phone1',
        ),
        migrations.AddField(
            model_name='application_form',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
