# Generated by Django 4.0.3 on 2022-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_application_form_phone1_application_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='email',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='father',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='application'),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='mother',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
