# Generated by Django 4.0.3 on 2022-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_form_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_form',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='father',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='file',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='name',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='phone',
        ),
        migrations.AddField(
            model_name='application_form',
            name='accession_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='any_deceased_parent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='cell_numbers',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='child_full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='citizenship',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='city_or_suburb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='copy_of_birth_certificate',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='application'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='copy_of_immunisation_records',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='application'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='country_province_and_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='dexterity_of_learner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='doctor_address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='doctor_phone_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='email_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='emergency_numbers',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='employer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='enter_their_names',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='first_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='gender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='grade_applied_for',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='highest_grade_passed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='home_langauge',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='home_language',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='identification_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='marital_status_of_parent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='medical_aid_main_member',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='medical_aid_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='medical_aid_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='medical_condition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='mode_of_transport',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='name_of_previous_school',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='number_of_other_children_at_mayfair',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='occupation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='other_names',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='parent_gender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='parent_race',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='parent_second_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='passport_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='physical_address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='pre_primary_education',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='preferred_lang_of_instruction',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='previous_school_address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='progress_report_previous_school',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='application'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='province_of_residence',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='race',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='registered_for_social_grant',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='relationship_to_learner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='religion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='spouse_id_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='surname_of_spouse',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='transfer_letter_previous_school',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='application'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='year_grade_passed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
