# Generated by Django 4.0.3 on 2022-05-04 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_form_copy_of_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
