# Generated by Django 4.0.3 on 2022-05-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline_one', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline_two', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_three', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_four', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_five', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline_six', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_seven', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_eight', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_nine', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline_ten', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_eleven', models.TextField(blank=True, max_length=200, null=True)),
                ('tagline_twelve', models.TextField(blank=True, max_length=200, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Sliders',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
