# Generated by Django 4.0.3 on 2022-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_r', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Our_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('title_one', models.CharField(blank=True, max_length=200, null=True)),
                ('title_two', models.CharField(blank=True, max_length=200, null=True)),
                ('description_one', models.TextField(blank=True, max_length=500, null=True)),
                ('description_two', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Our Activities',
                'verbose_name_plural': 'Our Activities',
            },
        ),
        migrations.CreateModel(
            name='Our_Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Our Class',
                'verbose_name_plural': 'Our Class',
            },
        ),
        migrations.CreateModel(
            name='Our_Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Our Mission',
                'verbose_name_plural': 'Our Mission',
            },
        ),
        migrations.CreateModel(
            name='Our_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(blank=True, max_length=200, null=True)),
                ('role_one', models.CharField(blank=True, max_length=200, null=True)),
                ('description_one', models.TextField(blank=True, max_length=200, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Our Staff',
                'verbose_name_plural': 'Our Staff',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_eight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_eleven',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_seven',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_six',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_ten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_twelve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
