# Generated by Django 4.0.3 on 2022-05-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_r', '0002_images_our_activities_our_classes_our_mission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Our_Staff',
        ),
    ]
