# Generated by Django 4.0.3 on 2022-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='brief_hsitory',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='director_welcome',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
