# Generated by Django 4.0.3 on 2022-03-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_rename_phone_number_our_mission_pass_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='our_mission',
            name='achievements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
