# Generated by Django 4.1.1 on 2022-09-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_slider_three_slider_two_rename_slider_slider_one_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider_three',
            new_name='Slider',
        ),
        migrations.DeleteModel(
            name='Slider_one',
        ),
        migrations.DeleteModel(
            name='Slider_two',
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Sliders', 'verbose_name_plural': 'Sliders'},
        ),
    ]
