# Generated by Django 4.1.1 on 2022-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_rename_slider_three_slider_delete_slider_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='tagline_four',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_five',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_six',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_three',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
