# Generated by Django 4.1.1 on 2022-09-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_rename_image_slider_image_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='title_one',
            new_name='title',
        ),
    ]
