# Generated by Django 4.1.1 on 2022-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_rename_tagline_five_impression_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mid_page',
            name='description_four',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mid_page',
            name='description_one',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mid_page',
            name='description_three',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mid_page',
            name='description_two',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mid_page',
            name='heading_one',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mid_page',
            name='heading_three',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mid_page',
            name='heading_two',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
