# Generated by Django 4.1.1 on 2022-09-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_mid_page_description_four_mid_page_description_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_six',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_eight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tagline_seven',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_five',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_six',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
