# Generated by Django 4.1.1 on 2022-10-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0014_slider_image_four_slider_image_six_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_six',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='tagline_eight',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='tagline_seven',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_five',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_four',
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline_six',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
