# Generated by Django 4.1.1 on 2022-10-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0015_remove_slider_image_four_remove_slider_image_six_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image_one',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='tagline_five',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='tagline_four',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='tagline_six',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='tagline_three',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_three',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_two',
        ),
    ]
